
// Objective-C API for talking to the following Go packages
//
//	github.com/cadmean-ru/amphion/frontend/ios/iosCli
//	github.com/cadmean-ru/amphion/frontend/cli
//	github.com/cadmean-ru/amphion/common/atext
//	github.com/cadmean-ru/amphion/common/dispatch
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Amphion_FRAMEWORK_H__
#define __Amphion_FRAMEWORK_H__

#include "IosCli.objc.h"
#include "Cli.objc.h"
#include "Atext.objc.h"
#include "Dispatch.objc.h"
#include "Universe.objc.h"

#endif
