// Objective-C API for talking to github.com/cadmean-ru/amphion/frontend/ios/iosCli Go package.
//   gobind -lang=objc github.com/cadmean-ru/amphion/frontend/ios/iosCli
//
// File is generated by gobind. Do not edit.

#ifndef __IosCli_H__
#define __IosCli_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"

#include "Cli.objc.h"

FOUNDATION_EXPORT void IosCliAmphionInit(id<CliFrontendDelegate> _Nullable f, id<CliResourceManagerDelegate> _Nullable rm, id<CliRendererDelegate> _Nullable rd);

FOUNDATION_EXPORT void IosCliRegisterPrimitiveRendererDelegate(long primitiveKind, id<CliPrimitiveRendererDelegate> _Nullable delegate);

#endif
