
package builtin

// This file is automatically generated
// DO NOT EDIT THIS FILE MANUALLY!!!

import (
	"github.com/cadmean-ru/amphion/engine"

)


func GetEventListener(so *engine.SceneObject, includeDirty ...bool) *EventListener {
	return so.GetComponentByName("github.com/cadmean-ru/amphion/engine/builtin.EventListener", includeDirty...).(*EventListener)
}

func FindEventListener(so *engine.SceneObject, includeDirty ...bool) *EventListener {
	return so.FindComponentByName("github.com/cadmean-ru/amphion/engine/builtin.EventListener", includeDirty...).(*EventListener)
}

func GetShapeView(so *engine.SceneObject, includeDirty ...bool) *ShapeView {
	return so.GetComponentByName("github.com/cadmean-ru/amphion/engine/builtin.ShapeView", includeDirty...).(*ShapeView)
}

func FindShapeView(so *engine.SceneObject, includeDirty ...bool) *ShapeView {
	return so.FindComponentByName("github.com/cadmean-ru/amphion/engine/builtin.ShapeView", includeDirty...).(*ShapeView)
}

func GetTriangleBoundary(so *engine.SceneObject, includeDirty ...bool) *TriangleBoundary {
	return so.GetComponentByName("github.com/cadmean-ru/amphion/engine/builtin.TriangleBoundary", includeDirty...).(*TriangleBoundary)
}

func FindTriangleBoundary(so *engine.SceneObject, includeDirty ...bool) *TriangleBoundary {
	return so.FindComponentByName("github.com/cadmean-ru/amphion/engine/builtin.TriangleBoundary", includeDirty...).(*TriangleBoundary)
}

func GetDropdownView(so *engine.SceneObject, includeDirty ...bool) *DropdownView {
	return so.GetComponentByName("github.com/cadmean-ru/amphion/engine/builtin.DropdownView", includeDirty...).(*DropdownView)
}

func FindDropdownView(so *engine.SceneObject, includeDirty ...bool) *DropdownView {
	return so.FindComponentByName("github.com/cadmean-ru/amphion/engine/builtin.DropdownView", includeDirty...).(*DropdownView)
}

func GetRectBoundary(so *engine.SceneObject, includeDirty ...bool) *RectBoundary {
	return so.GetComponentByName("github.com/cadmean-ru/amphion/engine/builtin.RectBoundary", includeDirty...).(*RectBoundary)
}

func FindRectBoundary(so *engine.SceneObject, includeDirty ...bool) *RectBoundary {
	return so.FindComponentByName("github.com/cadmean-ru/amphion/engine/builtin.RectBoundary", includeDirty...).(*RectBoundary)
}

func GetImageView(so *engine.SceneObject, includeDirty ...bool) *ImageView {
	return so.GetComponentByName("github.com/cadmean-ru/amphion/engine/builtin.ImageView", includeDirty...).(*ImageView)
}

func FindImageView(so *engine.SceneObject, includeDirty ...bool) *ImageView {
	return so.FindComponentByName("github.com/cadmean-ru/amphion/engine/builtin.ImageView", includeDirty...).(*ImageView)
}

func GetGridLayout(so *engine.SceneObject, includeDirty ...bool) *GridLayout {
	return so.GetComponentByName("github.com/cadmean-ru/amphion/engine/builtin.GridLayout", includeDirty...).(*GridLayout)
}

func FindGridLayout(so *engine.SceneObject, includeDirty ...bool) *GridLayout {
	return so.FindComponentByName("github.com/cadmean-ru/amphion/engine/builtin.GridLayout", includeDirty...).(*GridLayout)
}

func GetBuilderComponent(so *engine.SceneObject, includeDirty ...bool) *BuilderComponent {
	return so.GetComponentByName("github.com/cadmean-ru/amphion/engine/builtin.BuilderComponent", includeDirty...).(*BuilderComponent)
}

func FindBuilderComponent(so *engine.SceneObject, includeDirty ...bool) *BuilderComponent {
	return so.FindComponentByName("github.com/cadmean-ru/amphion/engine/builtin.BuilderComponent", includeDirty...).(*BuilderComponent)
}

func GetTextView(so *engine.SceneObject, includeDirty ...bool) *TextView {
	return so.GetComponentByName("github.com/cadmean-ru/amphion/engine/builtin.TextView", includeDirty...).(*TextView)
}

func FindTextView(so *engine.SceneObject, includeDirty ...bool) *TextView {
	return so.FindComponentByName("github.com/cadmean-ru/amphion/engine/builtin.TextView", includeDirty...).(*TextView)
}

func GetCircleBoundary(so *engine.SceneObject, includeDirty ...bool) *CircleBoundary {
	return so.GetComponentByName("github.com/cadmean-ru/amphion/engine/builtin.CircleBoundary", includeDirty...).(*CircleBoundary)
}

func FindCircleBoundary(so *engine.SceneObject, includeDirty ...bool) *CircleBoundary {
	return so.FindComponentByName("github.com/cadmean-ru/amphion/engine/builtin.CircleBoundary", includeDirty...).(*CircleBoundary)
}

func GetBezierView(so *engine.SceneObject, includeDirty ...bool) *BezierView {
	return so.GetComponentByName("github.com/cadmean-ru/amphion/engine/builtin.BezierView", includeDirty...).(*BezierView)
}

func FindBezierView(so *engine.SceneObject, includeDirty ...bool) *BezierView {
	return so.FindComponentByName("github.com/cadmean-ru/amphion/engine/builtin.BezierView", includeDirty...).(*BezierView)
}

func GetClipArea(so *engine.SceneObject, includeDirty ...bool) *ClipArea {
	return so.GetComponentByName("github.com/cadmean-ru/amphion/engine/builtin.ClipArea", includeDirty...).(*ClipArea)
}

func FindClipArea(so *engine.SceneObject, includeDirty ...bool) *ClipArea {
	return so.FindComponentByName("github.com/cadmean-ru/amphion/engine/builtin.ClipArea", includeDirty...).(*ClipArea)
}

func GetBoundaryView(so *engine.SceneObject, includeDirty ...bool) *BoundaryView {
	return so.GetComponentByName("github.com/cadmean-ru/amphion/engine/builtin.BoundaryView", includeDirty...).(*BoundaryView)
}

func FindBoundaryView(so *engine.SceneObject, includeDirty ...bool) *BoundaryView {
	return so.FindComponentByName("github.com/cadmean-ru/amphion/engine/builtin.BoundaryView", includeDirty...).(*BoundaryView)
}

func GetOnClickListener(so *engine.SceneObject, includeDirty ...bool) *OnClickListener {
	return so.GetComponentByName("github.com/cadmean-ru/amphion/engine/builtin.OnClickListener", includeDirty...).(*OnClickListener)
}

func FindOnClickListener(so *engine.SceneObject, includeDirty ...bool) *OnClickListener {
	return so.FindComponentByName("github.com/cadmean-ru/amphion/engine/builtin.OnClickListener", includeDirty...).(*OnClickListener)
}

func GetNativeInputView(so *engine.SceneObject, includeDirty ...bool) *NativeInputView {
	return so.GetComponentByName("github.com/cadmean-ru/amphion/engine/builtin.NativeInputView", includeDirty...).(*NativeInputView)
}

func FindNativeInputView(so *engine.SceneObject, includeDirty ...bool) *NativeInputView {
	return so.FindComponentByName("github.com/cadmean-ru/amphion/engine/builtin.NativeInputView", includeDirty...).(*NativeInputView)
}

func GetMouseMover(so *engine.SceneObject, includeDirty ...bool) *MouseMover {
	return so.GetComponentByName("github.com/cadmean-ru/amphion/engine/builtin.MouseMover", includeDirty...).(*MouseMover)
}

func FindMouseMover(so *engine.SceneObject, includeDirty ...bool) *MouseMover {
	return so.FindComponentByName("github.com/cadmean-ru/amphion/engine/builtin.MouseMover", includeDirty...).(*MouseMover)
}

